const feedData = [
    {
        id: '1',
        user: 'Michael',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '2 hours ago',
        content: 'Enjoying a beautiful day at the beach!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS85mi3mN2yPc5vDPHsVN1kgh-bKHCbveKN4g&s',
    },
    {
        id: '2',
        user: 'Trevor',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '3 hours ago',
        content: 'Had a great time with friends at the park.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnDHnW5kG7dB0zRAuAI1arbCCxMMFmbqCPtg&s',
    },
    {
        id: '3',
        user: 'Michael Brown',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw_CtvIHBe7KolQPBAzHCYk1F3Z8X1IFc0fQ&s',
    },
    {
        id: '4',
        user: 'Amanda',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB04Ac3yFf9oBuEbtQA8fULrZMX50wIlYZMg&s',
    },
    {
        id: '5',
        user: 'Lamar',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9TRGm5d9kj9CnZzg3s17Su2SV4tMvHMnjvg&s',
    },
    {
        id: '6',
        user: 'Joy',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOhJ_-3NWgDn20LIn5B-ArM6ExZlMZJ58nTw&s',
    },
    {
        id: '7',
        user: 'Tracy',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc3PZdtQwBSe8Dk3ZoolfY0ZyTV6oHx2uCQw&s',
    },
    {
        id: '8',
        user: 'Jimmy',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7vusdjaQgztry7z7kpvNwsvgCbDaSYcAT-Q&s',
    },
    {
        id: '9',
        user: 'Lester',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLLsWjQIutaMpCq-zVYV2uXLoCy5xYRhbKyQ&s',
    },
    {
        id: '10',
        user: 'Devin',
        userImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJVUQ3-68U6WNhaDWGbo-IZk-rRJBO1SVqw&s',
        time: '5 hours ago',
        content: 'Just finished a fantastic book. Highly recommend it!',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE-gwqKz7sqQNI3o2-HR_Yi7zG7mXk9KeU_g&s',
    },
];

export default feedData;
